[package]
name = "hedera"
version = "0.1.0"
edition = "2018"
authors = [
    "Ryan Leckey <ryan@launchbadge.com>"
]

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
# nightly enables various feature toggles and is recommended for security
# asm optimizes the sha2 crate
ed25519-dalek = { version = "0.8.1", default-features = false, features = [ "std", "nightly", "asm", "u64_backend" ] }
rand = "0.5.5"
# NOTE: Blocked on updating this by https://github.com/dalek-cryptography/ed25519-dalek/issues/46
sha2 = "0.7.0"
hex = "0.3.2"
failure = "0.1.3"
simple_asn1 = "0.1.0"
failure_derive = "0.1.3"
once_cell = { version = "0.1.6", features = [ "parking_lot" ] }
num = "0.2.0"
# NOTE: This must be synced with the version in [grpcio]
protobuf = "~2.0"
libc = "0.2.43"
mbox = "0.5.0"
itertools = "0.7.8"
grpcio = { version = "0.4.0", default-features = false, features = [ "protobuf-codec" ] }
futures = "0.1.25"
chrono = "0.4.6"
# unstable is required to allow non-copy types in the SlotMap (the `Error` types)
slotmap = { version = "0.3.0", features = [ "unstable" ] }
parking_lot = "0.6.4"

[build-dependencies]
protoc-grpcio = "0.3.0"
glob = "0.2.11"

[patch.crates-io]
# Unreleased
simple_asn1 = { git = "https://github.com/acw/simple_asn1.git", rev = "daf9cf18fdea18fb42a004e05ab1f1da9d4123eb" }
# Dependency upgrade
# https://github.com/mtp401/protoc-grpcio/pull/12
protoc-grpcio = { git = "https://github.com/mehcode/protoc-grpcio", rev = "7a704d72998d06b307d1632af2f79dbc235d9049" }

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
incremental = false
